-- =====================================================================
-- V1 — Baseline du schéma existant
-- =====================================================================
--
-- Capture du schéma tel que Hibernate l'avait généré (ddl-auto=update) au
-- moment de l'introduction de Flyway. Généré par :
--
--   pg_dump --schema-only --no-owner --no-privileges --no-comments
--
-- Les méta-commandes psql (\restrict, \unrestrict), les directives SET de
-- session et l'appel à pg_catalog.set_config ont été retirés : Flyway exécute
-- ce fichier via JDBC, qui ne les comprend pas.
--
-- DEUX COMPORTEMENTS, UN SEUL FICHIER
-- -----------------------------------
--  * Base VIDE (Mini PC, premier démarrage) : aucune table, aucun historique
--    Flyway → ce script s'exécute et CRÉE les tables. C'est ce qui permet à
--    l'application de démarrer alors que le profil prod impose
--    ddl-auto=validate (Hibernate vérifie, il ne crée plus rien).
--  * Base DÉJÀ PEUPLÉE (poste de développement) : les tables existent mais
--    l'historique Flyway est absent → baseline-on-migrate=true fait poser un
--    repère à la version 1 et ce script est SAUTÉ. Les données existantes ne
--    sont donc jamais touchées.
--
-- RÈGLE À TENIR
-- ------------
-- Ce fichier est immuable. Toute évolution ultérieure du schéma passe par un
-- nouveau fichier V2__..., V3__... ; modifier un script déjà appliqué casse la
-- validation de checksum de Flyway.
--
-- Périmètre : 25 tables, colonnes d'identité, contraintes et index tels que
-- constatés. Aucune évolution de schéma n'est introduite ici — en particulier
-- la colonne exemption_rate n'en fait volontairement PAS partie.
-- =====================================================================


--
-- Name: administrator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administrator (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    address character varying(255),
    city character varying(255),
    communication_preference character varying(255),
    date_of_birth date,
    email character varying(255),
    first_name character varying(255),
    gender character varying(255),
    last_name character varying(255),
    nationality character varying(255),
    phone_number character varying(255),
    photo character varying(255),
    place_of_birth character varying(255),
    password character varying(255),
    username character varying(255)
);

--
-- Name: administrator_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.administrator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administrator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: administrator_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administrator_roles (
    administrator_id bigint NOT NULL,
    role_id bigint NOT NULL
);

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'VIEWER'::character varying])::text[])))
);

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    catch_up_right boolean,
    is_catch_up boolean,
    is_justified boolean,
    status boolean,
    group_id bigint,
    missed_session_id bigint,
    session_id bigint,
    session_series_id bigint,
    student_id bigint
);

--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: catch_up_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.catch_up_request (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    cancellation_reason character varying(255),
    completed_date timestamp(6) without time zone,
    notes character varying(255),
    request_date timestamp(6) without time zone,
    scheduled_date timestamp(6) without time zone,
    status character varying(255),
    catch_up_group_id bigint,
    catch_up_session_id bigint,
    original_attendance_id bigint,
    original_group_id bigint,
    original_session_id bigint,
    student_id bigint,
    CONSTRAINT catch_up_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

--
-- Name: catch_up_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.catch_up_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catch_up_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: discount; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discount (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    group_id bigint,
    rate numeric(3,2),
    scope character varying(255),
    series_id bigint,
    session_id bigint,
    student_id bigint,
    CONSTRAINT discount_scope_check CHECK (((scope)::text = ANY ((ARRAY['GROUP'::character varying, 'SERIES'::character varying, 'SESSION'::character varying])::text[])))
);

--
-- Name: discount_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.discount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: group_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_types (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    name character varying(255),
    size integer
);

--
-- Name: group_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    name character varying(255),
    photo character varying(255),
    session_per_serie integer,
    group_type_id bigint,
    level_id bigint,
    price_id bigint,
    school_year_id bigint,
    subject_id bigint,
    teacher_id bigint
);

--
-- Name: groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: level; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.level (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    level_code character varying(255),
    level_sequence integer,
    name character varying(255)
);

--
-- Name: level_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.level ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.level_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payment_carry_over; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_carry_over (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    amount numeric(12,2) NOT NULL,
    origin_payment_date timestamp(6) without time zone,
    source_series_id bigint NOT NULL,
    student_id bigint NOT NULL,
    target_payment_id bigint NOT NULL,
    target_series_id bigint NOT NULL
);

--
-- Name: payment_carry_over_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_carry_over ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_carry_over_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payment_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_detail (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    amount_paid double precision NOT NULL,
    is_catch_up boolean,
    payment_date timestamp(6) without time zone,
    permanently_deleted boolean,
    payment_id bigint NOT NULL,
    session_id bigint
);

--
-- Name: payment_detail_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_detail_audit (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    new_value text,
    old_value text,
    payment_detail_id bigint NOT NULL,
    performed_by character varying(255) NOT NULL,
    reason text,
    "timestamp" timestamp(6) without time zone NOT NULL
);

--
-- Name: payment_detail_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_detail_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_detail_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payment_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    amount_paid double precision NOT NULL,
    notes character varying(1000),
    payment_date timestamp(6) without time zone,
    payment_for_month timestamp(6) without time zone,
    payment_method character varying(255),
    status character varying(255),
    group_id bigint,
    session_id bigint,
    session_series_id bigint,
    student_id bigint NOT NULL
);

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: price; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.price (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    effective_date timestamp(6) without time zone,
    expiration_date timestamp(6) without time zone,
    price double precision
);

--
-- Name: price_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.price ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: refund; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refund (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    amount numeric(12,2),
    refund_date timestamp(6) without time zone,
    payment_id bigint,
    student_id bigint
);

--
-- Name: refund_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refund ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(20) NOT NULL,
    CONSTRAINT role_name_check CHECK (((name)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_TEACHER'::character varying, 'ROLE_STUDENT'::character varying, 'ROLE_PARENT'::character varying])::text[])))
);

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    capacity integer,
    name character varying(255)
);

--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: school_year; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_year (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    end_date date NOT NULL,
    is_current boolean NOT NULL,
    label character varying(255) NOT NULL,
    start_date date NOT NULL
);

--
-- Name: school_year_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_year ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_year_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    feedback_link character varying(255),
    is_finished boolean,
    session_time_end timestamp(6) without time zone,
    session_time_start timestamp(6) without time zone,
    session_type character varying(255),
    title character varying(255),
    group_id bigint,
    room_id bigint,
    session_series_id bigint,
    teacher_id bigint
);

--
-- Name: session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: session_series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_series (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    name character varying(255),
    serie_time_end timestamp(6) without time zone,
    serie_time_start timestamp(6) without time zone,
    sessions_completed integer,
    total_sessions integer,
    group_id bigint
);

--
-- Name: session_series_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: student; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    address character varying(255),
    city character varying(255),
    communication_preference character varying(255),
    date_of_birth date,
    email character varying(255),
    first_name character varying(255),
    gender character varying(255),
    last_name character varying(255),
    nationality character varying(255),
    phone_number character varying(255),
    photo character varying(255),
    place_of_birth character varying(255),
    average_score double precision,
    establishment character varying(255),
    status character varying(255),
    level_id bigint,
    tutor_id bigint,
    CONSTRAINT student_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

--
-- Name: student_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_groups (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    date_assigned timestamp(6) without time zone,
    group_id bigint,
    student_id bigint
);

--
-- Name: student_groups_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.student_groups_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: subject; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subject (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    name character varying(255)
);

--
-- Name: subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: teacher; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    address character varying(255),
    city character varying(255),
    communication_preference character varying(255),
    date_of_birth date,
    email character varying(255),
    first_name character varying(255),
    gender character varying(255),
    last_name character varying(255),
    nationality character varying(255),
    phone_number character varying(255),
    photo character varying(255),
    place_of_birth character varying(255),
    specialization character varying(255),
    years_of_experience integer
);

--
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tutor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutor (
    id bigint NOT NULL,
    active boolean,
    created_by character varying(255),
    date_creation timestamp(6) without time zone,
    date_update timestamp(6) without time zone,
    description character varying(255),
    updated_by character varying(255),
    address character varying(255),
    city character varying(255),
    communication_preference character varying(255),
    date_of_birth date,
    email character varying(255),
    first_name character varying(255),
    gender character varying(255),
    last_name character varying(255),
    nationality character varying(255),
    phone_number character varying(255),
    photo character varying(255),
    place_of_birth character varying(255),
    occupation character varying(255),
    relationship character varying(255)
);

--
-- Name: tutor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tutor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tutor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: administrator administrator_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrator
    ADD CONSTRAINT administrator_pkey PRIMARY KEY (id);

--
-- Name: administrator_roles administrator_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrator_roles
    ADD CONSTRAINT administrator_roles_pkey PRIMARY KEY (administrator_id, role_id);

--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);

--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);

--
-- Name: catch_up_request catch_up_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT catch_up_request_pkey PRIMARY KEY (id);

--
-- Name: discount discount_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discount
    ADD CONSTRAINT discount_pkey PRIMARY KEY (id);

--
-- Name: group_types group_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_types
    ADD CONSTRAINT group_types_pkey PRIMARY KEY (id);

--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);

--
-- Name: level level_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.level
    ADD CONSTRAINT level_pkey PRIMARY KEY (id);

--
-- Name: payment_carry_over payment_carry_over_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_carry_over
    ADD CONSTRAINT payment_carry_over_pkey PRIMARY KEY (id);

--
-- Name: payment_detail_audit payment_detail_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_detail_audit
    ADD CONSTRAINT payment_detail_audit_pkey PRIMARY KEY (id);

--
-- Name: payment_detail payment_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_detail
    ADD CONSTRAINT payment_detail_pkey PRIMARY KEY (id);

--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

--
-- Name: price price_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price
    ADD CONSTRAINT price_pkey PRIMARY KEY (id);

--
-- Name: refund refund_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund
    ADD CONSTRAINT refund_pkey PRIMARY KEY (id);

--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);

--
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);

--
-- Name: school_year school_year_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_year
    ADD CONSTRAINT school_year_pkey PRIMARY KEY (id);

--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);

--
-- Name: session_series session_series_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_series
    ADD CONSTRAINT session_series_pkey PRIMARY KEY (id);

--
-- Name: student_groups student_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT student_groups_pkey PRIMARY KEY (id);

--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);

--
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);

--
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);

--
-- Name: tutor tutor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutor
    ADD CONSTRAINT tutor_pkey PRIMARY KEY (id);

--
-- Name: role uk8sewwnpamngi6b1dwaa88askk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT uk8sewwnpamngi6b1dwaa88askk UNIQUE (name);

--
-- Name: school_year uk_school_year_label; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_year
    ADD CONSTRAINT uk_school_year_label UNIQUE (label);

--
-- Name: app_user uk_user_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk_user_username UNIQUE (username);

--
-- Name: catch_up_request fk1obxt3mvq792mfabg5sosogw2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT fk1obxt3mvq792mfabg5sosogw2 FOREIGN KEY (catch_up_session_id) REFERENCES public.session(id);

--
-- Name: catch_up_request fk1qklnulvg1747a350amv4ac8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT fk1qklnulvg1747a350amv4ac8g FOREIGN KEY (original_session_id) REFERENCES public.session(id);

--
-- Name: catch_up_request fk26po24y01qxyfg0i2jdhcqj8t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT fk26po24y01qxyfg0i2jdhcqj8t FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: discount fk2iwdim7ciqlybx5v0qyermq49; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discount
    ADD CONSTRAINT fk2iwdim7ciqlybx5v0qyermq49 FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: session_series fk3n8gtp8rcg2ikxs8jlx31g0u3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_series
    ADD CONSTRAINT fk3n8gtp8rcg2ikxs8jlx31g0u3 FOREIGN KEY (group_id) REFERENCES public.groups(id);

--
-- Name: groups fk4xo9sa0lg1t1wb6wuoiskjgh3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fk4xo9sa0lg1t1wb6wuoiskjgh3 FOREIGN KEY (school_year_id) REFERENCES public.school_year(id);

--
-- Name: refund fk581oxhymt33w7nwt5daxpj91s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund
    ADD CONSTRAINT fk581oxhymt33w7nwt5daxpj91s FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: administrator_roles fk6ppshfah8k9n1tj1nlhnn2g1u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrator_roles
    ADD CONSTRAINT fk6ppshfah8k9n1tj1nlhnn2g1u FOREIGN KEY (role_id) REFERENCES public.role(id);

--
-- Name: groups fk7eqls3k4msk9oqw37ya84oekp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fk7eqls3k4msk9oqw37ya84oekp FOREIGN KEY (price_id) REFERENCES public.price(id);

--
-- Name: groups fk7keiy5sb9vqp56g9fvcjnf4wr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fk7keiy5sb9vqp56g9fvcjnf4wr FOREIGN KEY (level_id) REFERENCES public.level(id);

--
-- Name: payment_carry_over fk7oqr5im3d3gt2ylcq2k3byujs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_carry_over
    ADD CONSTRAINT fk7oqr5im3d3gt2ylcq2k3byujs FOREIGN KEY (source_series_id) REFERENCES public.session_series(id);

--
-- Name: payment_detail fk8720pquu0s4t96ba1bhau0oq6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_detail
    ADD CONSTRAINT fk8720pquu0s4t96ba1bhau0oq6 FOREIGN KEY (session_id) REFERENCES public.session(id);

--
-- Name: attendance fka9iwukl8v6di9d1pn870o79i6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fka9iwukl8v6di9d1pn870o79i6 FOREIGN KEY (session_series_id) REFERENCES public.session_series(id);

--
-- Name: groups fkai1f3kongcduihmwps7x5kypt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkai1f3kongcduihmwps7x5kypt FOREIGN KEY (group_type_id) REFERENCES public.group_types(id);

--
-- Name: payment_carry_over fkax3sl00uq2o6lyfn5s8fkvo12; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_carry_over
    ADD CONSTRAINT fkax3sl00uq2o6lyfn5s8fkvo12 FOREIGN KEY (target_series_id) REFERENCES public.session_series(id);

--
-- Name: payment_detail fkba81jrq7hvvu35cmyn0wxkvef; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_detail
    ADD CONSTRAINT fkba81jrq7hvvu35cmyn0wxkvef FOREIGN KEY (payment_id) REFERENCES public.payments(id);

--
-- Name: session fkc58t0jaw2hy0utcp0ibau3xv4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkc58t0jaw2hy0utcp0ibau3xv4 FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);

--
-- Name: payments fkcbmx5bg9i0dw31voyc9gvtf4i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkcbmx5bg9i0dw31voyc9gvtf4i FOREIGN KEY (session_series_id) REFERENCES public.session_series(id);

--
-- Name: payment_carry_over fkch33trgvtupp18alkln9a7m29; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_carry_over
    ADD CONSTRAINT fkch33trgvtupp18alkln9a7m29 FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: attendance fkcpuoqswvhfmildrv4ug70in2b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkcpuoqswvhfmildrv4ug70in2b FOREIGN KEY (missed_session_id) REFERENCES public.session(id);

--
-- Name: student_groups fkdh4j89halvjp6bxmkayknn3um; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT fkdh4j89halvjp6bxmkayknn3um FOREIGN KEY (group_id) REFERENCES public.groups(id);

--
-- Name: payment_carry_over fkemcbbmhxxha4uqpl4wc2cqmaj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_carry_over
    ADD CONSTRAINT fkemcbbmhxxha4uqpl4wc2cqmaj FOREIGN KEY (target_payment_id) REFERENCES public.payments(id);

--
-- Name: groups fkh41v53xm83rq9vspgdjqjjsm2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkh41v53xm83rq9vspgdjqjjsm2 FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);

--
-- Name: student fkhouc0qse1o4wn2emncf5spsru; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkhouc0qse1o4wn2emncf5spsru FOREIGN KEY (level_id) REFERENCES public.level(id);

--
-- Name: attendance fkio7owk551ayxpc28li9ddwmkq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkio7owk551ayxpc28li9ddwmkq FOREIGN KEY (group_id) REFERENCES public.groups(id);

--
-- Name: refund fkj6e6w9vygi3b2w3ikwln6dp9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refund
    ADD CONSTRAINT fkj6e6w9vygi3b2w3ikwln6dp9 FOREIGN KEY (payment_id) REFERENCES public.payments(id);

--
-- Name: payments fkjeqnjw00iwcmqvpra9wjmicap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkjeqnjw00iwcmqvpra9wjmicap FOREIGN KEY (group_id) REFERENCES public.groups(id);

--
-- Name: catch_up_request fknlao6r9bgwe30ljx6dkij1qdn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT fknlao6r9bgwe30ljx6dkij1qdn FOREIGN KEY (original_group_id) REFERENCES public.groups(id);

--
-- Name: attendance fknq6vm31it076obtjf2qp5coim; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fknq6vm31it076obtjf2qp5coim FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: student fknq8hvnfuokc5y0gi1hqra5xul; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fknq8hvnfuokc5y0gi1hqra5xul FOREIGN KEY (tutor_id) REFERENCES public.tutor(id);

--
-- Name: payments fko0lgt74t3bsgmnfq54pcdew7y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fko0lgt74t3bsgmnfq54pcdew7y FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: session fko6vn2952ttw85h6ewh9nvy8xo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fko6vn2952ttw85h6ewh9nvy8xo FOREIGN KEY (group_id) REFERENCES public.groups(id);

--
-- Name: student_groups fkojsj5rrj0bn2n461wv97h7jon; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_groups
    ADD CONSTRAINT fkojsj5rrj0bn2n461wv97h7jon FOREIGN KEY (student_id) REFERENCES public.student(id);

--
-- Name: session fkoyfccms1psubki0cm7c92msrp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkoyfccms1psubki0cm7c92msrp FOREIGN KEY (room_id) REFERENCES public.room(id);

--
-- Name: groups fkpduc2peqan6ivl2y1gcpad4qd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkpduc2peqan6ivl2y1gcpad4qd FOREIGN KEY (subject_id) REFERENCES public.subject(id);

--
-- Name: session fkpm1aai2m9sjnkf06nfm6dx6sn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkpm1aai2m9sjnkf06nfm6dx6sn FOREIGN KEY (session_series_id) REFERENCES public.session_series(id);

--
-- Name: catch_up_request fkq9bct6341q2cgpe61ub0osw78; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT fkq9bct6341q2cgpe61ub0osw78 FOREIGN KEY (original_attendance_id) REFERENCES public.attendance(id);

--
-- Name: catch_up_request fkqd1wsx7lrv2kdlh30ykm1k8xt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.catch_up_request
    ADD CONSTRAINT fkqd1wsx7lrv2kdlh30ykm1k8xt FOREIGN KEY (catch_up_group_id) REFERENCES public.groups(id);

--
-- Name: attendance fkras5lsk62ds9j7f8myss8nwcs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkras5lsk62ds9j7f8myss8nwcs FOREIGN KEY (session_id) REFERENCES public.session(id);

--
-- Name: payments fksgn1k8gg8knf4ljhw1x0qyjsn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fksgn1k8gg8knf4ljhw1x0qyjsn FOREIGN KEY (session_id) REFERENCES public.session(id);

--
-- PostgreSQL database dump complete
--

