-- =====================================================================
-- V2 — Justification d'absence auditée, et remboursement traçable
-- Feature : absence-justification-and-refund-receipts
-- =====================================================================
--
-- PÉRIMÈTRE : DDL UNIQUEMENT, AUCUNE REPRISE DE DONNÉES
-- -----------------------------------------------------
-- Décision produit : l'existant ne compte pas. Les données actuelles sont des
-- données de test destinées à être supprimées, et l'installation cible démarre
-- sur une base vide. Ce script ne contient donc aucun rattrapage de lignes
-- passées : ni renumérotation de remboursements existants, ni rattachement de
-- présences orphelines, ni détection de doublons antérieurs.
--
-- Les contraintes posées ici protègent les données à VENIR, celles que
-- l'administrateur saisira. C'est leur seule raison d'être.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Journal d'audit de la justification d'absence (exigence 5)
-- ---------------------------------------------------------------------
-- attendance_id est une colonne SIMPLE, volontairement SANS clé étrangère,
-- sur le modèle de payment_detail_audit qui fait déjà ce choix dans ce
-- projet. C'est ce qui permet à la trace de survivre à la suppression de la
-- présence auditée (exigence 5.11) : une clé étrangère avec cascade
-- détruirait la preuve en même temps que son objet, or c'est précisément
-- après la disparition d'une donnée qu'on a besoin de savoir qui l'a
-- modifiée.
CREATE TABLE attendance_justification_audit (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id bigint       NOT NULL,
    old_value     boolean,
    new_value     boolean      NOT NULL,
    performed_by  varchar(255) NOT NULL,
    -- Précision milliseconde exigée par 5.1. sequence_rank départage deux
    -- entrées de même horodatage, ce qui rend l'ordre de restitution (5.7)
    -- et la valeur courante (5.8) déterministes.
    performed_at  timestamp(3) NOT NULL,
    sequence_rank bigint       NOT NULL,
    comment       text
);

-- Index calqué exactement sur l'ordre de restitution demandé par 5.7,
-- afin que la lecture de la piste d'audit n'ait rien à retrier.
CREATE INDEX idx_aja_attendance
    ON attendance_justification_audit (attendance_id, performed_at DESC, sequence_rank DESC);


-- ---------------------------------------------------------------------
-- 2. Motif et numéro de pièce du remboursement (exigence 6)
-- ---------------------------------------------------------------------
-- La table est vide : les colonnes sont donc posées directement dans leur
-- forme définitive, sans étape de remplissage intermédiaire.
--
-- reason reste nullable au niveau du schéma alors que le motif est
-- obligatoire : l'obligation est portée par RefundService, où le message
-- d'erreur peut expliquer pourquoi un motif est exigé. Une contrainte
-- NOT NULL produirait une violation de contrainte illisible à la place.
ALTER TABLE refund ADD COLUMN reason        text;
ALTER TABLE refund ADD COLUMN refund_number varchar(32) NOT NULL;

-- L'unicité est portée par le STOCKAGE et non par le calcul applicatif
-- (exigence 6.6) : elle vaut alors quel que soit le nombre d'instances de
-- l'application, et le service n'a plus qu'à rejouer sur collision (6.14).
ALTER TABLE refund ADD CONSTRAINT uk_refund_number UNIQUE (refund_number);


-- ---------------------------------------------------------------------
-- 3. Émissions de reçu de remboursement (exigence 8.10)
-- ---------------------------------------------------------------------
-- Ici la clé étrangère est légitime, contrairement au journal d'audit :
-- une émission de reçu n'a aucun sens sans son remboursement.
--
-- Un simple compteur sur refund aurait suffi à porter le rang exigé par
-- 8.10. Le journal est préféré parce que la réimpression d'un reçu de
-- caisse est exactement l'événement qu'on veut pouvoir retracer : un reçu
-- réimprimé peut servir deux fois.
CREATE TABLE refund_receipt_issuance (
    id        bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id bigint       NOT NULL,
    rank      integer      NOT NULL,
    issued_at timestamp(3) NOT NULL,
    issued_by varchar(255) NOT NULL,
    CONSTRAINT fk_rri_refund      FOREIGN KEY (refund_id) REFERENCES refund (id),
    CONSTRAINT uk_rri_refund_rank UNIQUE (refund_id, rank)
);

CREATE INDEX idx_rri_refund ON refund_receipt_issuance (refund_id);


-- ---------------------------------------------------------------------
-- 4. Un seul rattrapage par séance manquée (exigence 1.9)
-- ---------------------------------------------------------------------
-- Deux rattrapages actifs d'une même séance manquée rendraient le décompte
-- des séances suivies indéterminé. L'index l'empêche pour les saisies à
-- venir ; aucune détection de doublon passé n'est nécessaire, la base
-- étant vide.
--
-- L'index est PARTIEL, et il doit l'être : sans la clause WHERE, toutes les
-- présences ordinaires (missed_session_id nul) entreraient en collision
-- entre elles, et une présence désactivée bloquerait l'enregistrement d'un
-- nouveau rattrapage légitime.
CREATE UNIQUE INDEX uk_attendance_student_missed
    ON attendance (student_id, missed_session_id)
    WHERE missed_session_id IS NOT NULL AND active = true;
