-- =====================================================================
-- V3 — Routage et traçabilité de la facturation des rattrapages
-- Feature : catch-up-billing-routing
-- =====================================================================
--
-- PÉRIMÈTRE : DDL UNIQUEMENT, AUCUNE REPRISE DE DONNÉES
-- -----------------------------------------------------
-- Les présences de rattrapage déjà enregistrées sans séance manquée ne sont
-- PAS reclassées ici. Elles portent de l'argent déjà encaissé : leur
-- correction passe par un rapport en lecture seule, une décision explicite
-- du propriétaire produit, puis un script ciblant des identifiants nommés.
-- Un UPDATE large dans une migration de schéma modifierait des montants
-- reconnus sans que personne ne l'ait demandé.
--
-- Conséquence assumée : après ce script, les lignes existantes ont un état
-- nul. C'est lisible — « rattrapage d'avant le routage » — et sans effet sur
-- les montants, le résolveur ne traitant spécialement que PENDING.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. État de facturation du rattrapage
-- ---------------------------------------------------------------------
-- Stocké en texte (@Enumerated(STRING)) et non en ordinal : un ordinal
-- rendrait la base illisible et ferait silencieusement dériver le sens des
-- lignes existantes si l'ordre des valeurs de l'enum changeait un jour.
--
-- La colonne reste NULLABLE : une présence ordinaire n'est pas un rattrapage
-- et n'a aucun état de facturation à porter. Un NOT NULL obligerait à
-- inventer une valeur « sans objet » qui n'existe pas dans le domaine.
ALTER TABLE attendance ADD COLUMN catch_up_billing_state varchar(32);

-- Contrainte de domaine : l'application est l'autorité sur les transitions,
-- mais rien ne justifie de laisser entrer une valeur qui n'existe pas.
-- La clause NULL est explicite, sinon la contrainte rejetterait toutes les
-- présences ordinaires.
ALTER TABLE attendance ADD CONSTRAINT attendance_catch_up_billing_state_check
    CHECK (catch_up_billing_state IS NULL
           OR catch_up_billing_state IN ('PENDING', 'RESOLVED', 'HOST_BILLED'));


-- ---------------------------------------------------------------------
-- 2. Décision « la séance manquée était-elle déjà payée ? »
-- ---------------------------------------------------------------------
-- NULLABLE, et c'est le cœur de la règle : NULL signifie « non tranché »,
-- pas « non ». Le choix doit être explicite (aucune valeur par défaut), donc
-- l'état « pas encore décidé » doit être représentable. Poser DEFAULT false
-- reviendrait à décider à la place de l'administrateur, silencieusement.
ALTER TABLE attendance ADD COLUMN missed_session_already_paid boolean;


-- ---------------------------------------------------------------------
-- 3. Lecture des rattrapages à préciser
-- ---------------------------------------------------------------------
-- La liste « rattrapages en attente de décision » est consultée pour être
-- vidée : elle doit rester rapide même quand elle est longue. Index PARTIEL,
-- puisque seules les lignes PENDING actives y figurent.
CREATE INDEX idx_attendance_catch_up_pending
    ON attendance (student_id, session_id)
    WHERE catch_up_billing_state = 'PENDING' AND active = true;


-- ---------------------------------------------------------------------
-- 4. Journal d'audit des décisions de facturation d'un rattrapage
-- ---------------------------------------------------------------------
-- Même parti que attendance_justification_audit et payment_detail_audit :
-- attendance_id est une colonne SIMPLE, volontairement SANS clé étrangère.
-- La trace doit survivre à la suppression de la présence auditée — c'est
-- justement après la disparition d'une donnée qu'on a besoin de savoir qui
-- l'a modifiée, et une clé étrangère avec cascade détruirait la preuve en
-- même temps que son objet.
--
-- Les deux décisions corrigeables sont journalisées dans la même table :
-- field nomme celle qui a changé. Deux tables séparées obligeraient à
-- fusionner deux historiques pour relire la chronologie d'un rattrapage.
CREATE TABLE catch_up_billing_audit (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id bigint       NOT NULL,
    -- 'MISSED_SESSION' ou 'ALREADY_PAID'
    field         varchar(32)  NOT NULL,
    -- Valeurs rendues en texte : elles portent tantôt un identifiant de
    -- séance, tantôt un booléen. Une colonne typée par champ multiplierait
    -- les colonnes vides sans rien ajouter à la lecture.
    old_value     varchar(64),
    new_value     varchar(64),
    performed_by  varchar(255) NOT NULL,
    -- Précision milliseconde, et sequence_rank pour départager deux entrées
    -- de même horodatage : sans lui l'ordre de restitution ne serait pas
    -- déterministe, et « quelle est la dernière décision » resterait ambigu.
    performed_at  timestamp(3) NOT NULL,
    sequence_rank bigint       NOT NULL,
    comment       text,
    CONSTRAINT catch_up_billing_audit_field_check
        CHECK (field IN ('MISSED_SESSION', 'ALREADY_PAID'))
);

-- Index calqué sur l'ordre de restitution attendu, afin que la lecture de la
-- piste d'audit n'ait rien à retrier.
CREATE INDEX idx_cuba_attendance
    ON catch_up_billing_audit (attendance_id, performed_at DESC, sequence_rank DESC);

-- ---------------------------------------------------------------------
-- 5. État de paiement de la série d'origine, porté par la demande
-- ---------------------------------------------------------------------
-- Un retard de paiement REFUSAIT la demande de rattrapage (400). La règle
-- était rigide au mauvais endroit : elle interdisait à l'administrateur
-- d'accorder un rattrapage qu'il venait de décider, sans recours.
--
-- Le retard est désormais enregistré ici pour être AFFICHÉ à côté de la
-- décision « déjà payée ». NULLABLE : les demandes créées avant ce script
-- n'ont jamais porté cette information, et lui inventer une valeur
-- laisserait croire qu'un état de paiement a été constaté à leur création.
--
-- Ce champ n'entre dans AUCUN calcul monétaire : il informe, il ne facture pas.
ALTER TABLE catch_up_request ADD COLUMN missed_session_overdue boolean;
