-- =====================================================================
-- Encaissements et traces de correction (spec admin-corrections, lot A)
--
-- Jusqu'ici, un versement n'avait pas d'existence propre : `payments` ne
-- porte qu'un cumul par étudiant et par série, dont la date est réécrite à
-- chaque écriture, et une séance n'a qu'une ligne de ventilation que les
-- versements successifs viennent compléter. Annuler « le versement de
-- 14h32 » était donc impossible sans toucher aux autres.
--
-- Cette migration crée l'Encaissement — un versement tel qu'il a eu lieu —
-- et ses Imputations, une par série créditée. Elle ne transforme aucune
-- donnée : le système est en test, la base est réinitialisée avant
-- l'installation chez le client.
--
-- Liens vers l'Encaissement, sur les tables existantes : NULLABLES ici.
-- Le code n'écrit pas encore ces liens ; ils deviennent obligatoires dans
-- une migration ultérieure, livrée avec le code qui les écrit. Les rendre
-- obligatoires dès maintenant ferait échouer tout encaissement entre les
-- deux livraisons.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. L'Encaissement
-- ---------------------------------------------------------------------
CREATE TABLE encashment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Numéro imprimé sur le reçu, attribué par le serveur, jamais réutilisé.
    receipt_number      VARCHAR(32)    NOT NULL,

    student_id          BIGINT         NOT NULL,
    group_id            BIGINT         NOT NULL,
    -- Série visée à la saisie. Le surplus éventuel est imputé sur les séries
    -- suivantes : voir encashment_allocation.
    target_series_id    BIGINT         NOT NULL,

    -- Montant reçu, tel quel. Jamais modifié : une erreur se rectifie par
    -- annulation ou remplacement, pas en réécrivant l'argent reçu.
    amount_received     NUMERIC(12,2)  NOT NULL,
    payment_method      VARCHAR(50),
    notes               TEXT,
    kind                VARCHAR(20)    NOT NULL,

    -- Date et auteur fixés par le serveur, jamais par le poste client.
    received_at         TIMESTAMP(6)   NOT NULL,
    received_by         VARCHAR(255)   NOT NULL,

    status              VARCHAR(20)    NOT NULL,
    cancelled_at        TIMESTAMP(6),
    cancelled_by        VARCHAR(255),
    cancel_reason_type  VARCHAR(40),
    cancel_reason_text  VARCHAR(500),

    -- Remplacement : l'original annulé et son remplaçant se désignent l'un
    -- l'autre, pour que l'historique affiche les deux sens.
    replaces_id         BIGINT,
    replaced_by_id      BIGINT,

    CONSTRAINT fk_encashment_student      FOREIGN KEY (student_id)       REFERENCES student (id),
    CONSTRAINT fk_encashment_group        FOREIGN KEY (group_id)         REFERENCES groups (id),
    CONSTRAINT fk_encashment_series       FOREIGN KEY (target_series_id) REFERENCES session_series (id),
    CONSTRAINT fk_encashment_replaces     FOREIGN KEY (replaces_id)      REFERENCES encashment (id),
    CONSTRAINT fk_encashment_replaced_by  FOREIGN KEY (replaced_by_id)   REFERENCES encashment (id),

    -- Un versement nul ou négatif n'encaisse rien.
    CONSTRAINT ck_encashment_amount_positive CHECK (amount_received > 0),
    CONSTRAINT ck_encashment_status          CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT ck_encashment_kind            CHECK (kind IN ('REGULAR', 'CATCH_UP')),
    -- Un encaissement annulé dit toujours quand, par qui et pourquoi ; un
    -- encaissement actif ne porte aucune trace d'annulation.
    --
    -- Un statut inconnu passe ici et reste refusé par ck_encashment_status :
    -- chaque contrainte a une seule responsabilité, pour que le refus nomme la
    -- vraie cause. PostgreSQL évalue les contraintes par ordre alphabétique,
    -- donc une règle d'annulation qui exigerait aussi un statut connu
    -- signalerait une annulation incomplète là où le statut est faux.
    CONSTRAINT ck_encashment_cancellation CHECK (
        CASE status
            WHEN 'CANCELLED' THEN
                cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL
                AND cancel_reason_type IS NOT NULL
            WHEN 'ACTIVE' THEN
                cancelled_at IS NULL AND cancelled_by IS NULL
                AND cancel_reason_type IS NULL AND cancel_reason_text IS NULL
            ELSE TRUE
        END),
    -- Le motif « Autre » n'a de sens qu'accompagné d'un texte.
    CONSTRAINT ck_encashment_cancel_reason_other CHECK (
        cancel_reason_type IS DISTINCT FROM 'OTHER'
        OR (cancel_reason_text IS NOT NULL AND length(btrim(cancel_reason_text)) > 0)),
    -- Un encaissement remplacé est forcément annulé.
    CONSTRAINT ck_encashment_replaced_is_cancelled CHECK (
        replaced_by_id IS NULL OR status = 'CANCELLED'),
    CONSTRAINT ck_encashment_not_self CHECK (replaces_id <> id AND replaced_by_id <> id)
);

-- La garantie réelle qu'un numéro de reçu ne sert qu'une fois.
CREATE UNIQUE INDEX uk_encashment_receipt_number ON encashment (receipt_number);
-- Historique des encaissements d'un étudiant, le plus récent d'abord.
CREATE INDEX idx_encashment_student ON encashment (student_id, received_at DESC);
CREATE INDEX idx_encashment_series  ON encashment (target_series_id);

-- ---------------------------------------------------------------------
-- 2. L'Imputation : la part d'un Encaissement créditée sur une série
-- ---------------------------------------------------------------------
-- Un encaissement crédite la série visée, puis, s'il la dépasse, les séries
-- suivantes par report. Une ligne par série créditée.
CREATE TABLE encashment_allocation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encashment_id   BIGINT         NOT NULL,
    series_id       BIGINT         NOT NULL,
    -- Cumul de la série pour cet étudiant. Il devient la somme des Imputations
    -- actives, au lieu d'être réécrit depuis la ventilation.
    payment_id      BIGINT         NOT NULL,
    amount          NUMERIC(12,2)  NOT NULL,
    carried_over    BOOLEAN        NOT NULL,
    -- Désactivée quand l'Encaissement est annulé : l'argent ne compte plus,
    -- la ligne reste pour l'historique.
    active          BOOLEAN        NOT NULL,

    CONSTRAINT fk_allocation_encashment FOREIGN KEY (encashment_id) REFERENCES encashment (id),
    CONSTRAINT fk_allocation_series     FOREIGN KEY (series_id)     REFERENCES session_series (id),
    CONSTRAINT fk_allocation_payment    FOREIGN KEY (payment_id)    REFERENCES payments (id),
    CONSTRAINT ck_allocation_amount_positive CHECK (amount > 0),
    -- Le plan d'imputation crédite chaque série au plus une fois.
    CONSTRAINT uk_allocation_encashment_series UNIQUE (encashment_id, series_id)
);

CREATE INDEX idx_allocation_payment ON encashment_allocation (payment_id);

-- ---------------------------------------------------------------------
-- 3. Liens des tables existantes
-- ---------------------------------------------------------------------
-- Une ligne de ventilation et un report sont chacun une PART d'une Imputation :
-- ils la désignent, et l'Encaissement s'en déduit. Les relier aussi
-- directement à l'Encaissement dupliquerait l'information, avec le risque de
-- deux valeurs contradictoires.
ALTER TABLE payment_detail
    ADD COLUMN encashment_allocation_id BIGINT,
    ADD CONSTRAINT fk_payment_detail_allocation
        FOREIGN KEY (encashment_allocation_id) REFERENCES encashment_allocation (id);
CREATE INDEX idx_payment_detail_allocation ON payment_detail (encashment_allocation_id);

ALTER TABLE payment_carry_over
    ADD COLUMN encashment_allocation_id BIGINT,
    ADD CONSTRAINT fk_payment_carry_over_allocation
        FOREIGN KEY (encashment_allocation_id) REFERENCES encashment_allocation (id);
CREATE INDEX idx_payment_carry_over_allocation ON payment_carry_over (encashment_allocation_id);

-- L'empreinte d'idempotence porte sur la requête entière, donc sur l'Encaissement.
ALTER TABLE payment_idempotency
    ADD COLUMN encashment_id BIGINT,
    ADD CONSTRAINT fk_payment_idempotency_encashment
        FOREIGN KEY (encashment_id) REFERENCES encashment (id);

-- ---------------------------------------------------------------------
-- 4. Trace commune des corrections
-- ---------------------------------------------------------------------
-- Aucune clé étrangère vers les données tracées : une trace doit survivre à la
-- disparition de ce qu'elle décrit, c'est précisément là qu'on en a besoin.
--
-- L'identifiant sert de rang : attribué par la base, strictement croissant
-- dans l'ordre des écritures, il départage deux corrections de la même
-- milliseconde. Un rang calculé par MAX + 1 laisserait deux écritures
-- simultanées obtenir le même.
CREATE TABLE correction_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain          VARCHAR(40)    NOT NULL,
    action          VARCHAR(40)    NOT NULL,
    entity_id       BIGINT         NOT NULL,
    student_id      BIGINT,
    group_id        BIGINT,
    session_id      BIGINT,
    series_id       BIGINT,
    -- Valeurs structurées, pour la machine.
    old_value       TEXT,
    new_value       TEXT,
    -- Phrase en français rédigée à l'écriture, quand toutes les données sont
    -- disponibles : la trace reste lisible si la donnée disparaît ensuite.
    summary         VARCHAR(500)   NOT NULL,
    -- Effet sur le montant dû, par exemple « dû 6 000,00 → 4 000,00 DA ».
    amount_effect   VARCHAR(500),
    reason_type     VARCHAR(40)    NOT NULL,
    reason_text     VARCHAR(500),
    performed_by    VARCHAR(255)   NOT NULL,
    performed_at    TIMESTAMP(6)   NOT NULL,

    CONSTRAINT ck_correction_reason_other CHECK (
        reason_type <> 'OTHER'
        OR (reason_text IS NOT NULL AND length(btrim(reason_text)) > 0))
);

-- Journal d'un étudiant, le plus récent d'abord.
CREATE INDEX idx_correction_audit_student ON correction_audit (student_id, id DESC);
