-- =====================================================================
-- V9 — Spec teacher-payroll, tâche P.1 : la Paie des enseignants
--
-- Un enseignant reçoit une part de ce que la série de son groupe a
-- réellement encaissé, au pourcentage choisi par l'administrateur dans un
-- catalogue (business-rules.md, « Paie des enseignants »). L'école garde le
-- reste.
--
-- Quatre tables :
--   1. teacher_pay_rate      le catalogue des taux, entretenu comme les tarifs ;
--   2. teacher_payout        une Paie, copie figée de sa base et de son taux ;
--   3. payout_counter        le compteur des numéros PAIE-AAAA-NNNN ;
--   4. payout_slip_issuance  chaque impression d'un bordereau (duplicata).
--
-- Structure seulement : aucune donnée ancienne n'est à reprendre.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Le catalogue des taux
-- ---------------------------------------------------------------------
-- Colonnes d'audit de BaseEntity, comme les autres référentiels. Un taux
-- n'est jamais supprimé : désactivé, il n'est plus proposé, et les paies qui
-- l'ont utilisé en gardent une copie.
CREATE TABLE teacher_pay_rate (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label            VARCHAR(100)   NOT NULL,
    -- Part de l'enseignant, en pourcentage ; l'école garde 100 − ce taux.
    teacher_percent  NUMERIC(5,2)   NOT NULL,
    active           BOOLEAN,
    description      VARCHAR(255),
    created_by       VARCHAR(255),
    date_creation    TIMESTAMP(6),
    updated_by       VARCHAR(255),
    date_update      TIMESTAMP(6),

    -- 0 % ne rémunère personne, 100 % ne laisse rien à l'école : deux parts
    -- doivent exister, sinon ce n'est pas un partage.
    CONSTRAINT ck_teacher_pay_rate_percent CHECK (teacher_percent > 0 AND teacher_percent < 100),
    CONSTRAINT ck_teacher_pay_rate_label   CHECK (length(btrim(label)) > 0)
);

-- Deux taux actifs de même libellé seraient indiscernables dans la liste du
-- dialogue de paie. Un taux désactivé libère son libellé.
CREATE UNIQUE INDEX uk_teacher_pay_rate_label
    ON teacher_pay_rate (lower(btrim(label))) WHERE active IS TRUE;

-- ---------------------------------------------------------------------
-- 2. La Paie
-- ---------------------------------------------------------------------
-- Une paie est une pièce de caisse : ses montants ne sont jamais modifiés.
-- L'argent arrivé ou rendu après coup donne une Régularisation, une erreur
-- se rectifie par annulation ou remplacement (spec, exigences 6 et 7).
CREATE TABLE teacher_payout (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_number       VARCHAR(32)    NOT NULL,
    kind                VARCHAR(20)    NOT NULL,
    -- Une Régularisation désigne la Paie_Initiale de sa série, dont elle reprend
    -- le pourcentage.
    initial_payout_id   BIGINT,

    teacher_id          BIGINT         NOT NULL,
    group_id            BIGINT         NOT NULL,
    series_id           BIGINT         NOT NULL,

    -- Copie figée du taux : le catalogue peut changer, la paie non. Le lien
    -- vers le taux ne sert qu'aux filtres et peut manquer.
    rate_id             BIGINT,
    rate_label          VARCHAR(100)   NOT NULL,
    teacher_percent     NUMERIC(5,2)   NOT NULL,

    -- Encaissé_Net couvert par cette paie, avec sa composition : brut moins
    -- remboursé. Ce que la paie partage est base_delta, la part de cet
    -- encaissé qu'aucune paie précédente de la série n'avait couverte.
    collected_gross     NUMERIC(12,2)  NOT NULL,
    refunded            NUMERIC(12,2)  NOT NULL,
    collected_net       NUMERIC(12,2)  NOT NULL,
    base_delta          NUMERIC(12,2)  NOT NULL,
    -- Négatif pour une Retenue : de l'argent a été rendu après la paie.
    teacher_amount      NUMERIC(12,2)  NOT NULL,
    school_amount       NUMERIC(12,2)  NOT NULL,

    note                TEXT,
    -- Date et auteur fixés par le serveur, jamais par le poste client.
    paid_at             TIMESTAMP(6)   NOT NULL,
    paid_by             VARCHAR(255)   NOT NULL,

    status              VARCHAR(20)    NOT NULL,
    cancelled_at        TIMESTAMP(6),
    cancelled_by        VARCHAR(255),
    cancel_reason_type  VARCHAR(40),
    cancel_reason_text  VARCHAR(500),
    replaces_id         BIGINT,
    replaced_by_id      BIGINT,

    CONSTRAINT fk_teacher_payout_initial     FOREIGN KEY (initial_payout_id) REFERENCES teacher_payout (id),
    CONSTRAINT fk_teacher_payout_teacher     FOREIGN KEY (teacher_id)        REFERENCES teacher (id),
    CONSTRAINT fk_teacher_payout_group       FOREIGN KEY (group_id)          REFERENCES groups (id),
    CONSTRAINT fk_teacher_payout_series      FOREIGN KEY (series_id)         REFERENCES session_series (id),
    CONSTRAINT fk_teacher_payout_rate        FOREIGN KEY (rate_id)           REFERENCES teacher_pay_rate (id),
    CONSTRAINT fk_teacher_payout_replaces    FOREIGN KEY (replaces_id)       REFERENCES teacher_payout (id),
    CONSTRAINT fk_teacher_payout_replaced_by FOREIGN KEY (replaced_by_id)    REFERENCES teacher_payout (id),

    CONSTRAINT ck_teacher_payout_kind    CHECK (kind IN ('INITIAL', 'REGULARIZATION')),
    CONSTRAINT ck_teacher_payout_status  CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT ck_teacher_payout_percent CHECK (teacher_percent > 0 AND teacher_percent < 100),
    -- L'encaissé net est le brut moins le remboursé, jamais une autre valeur.
    CONSTRAINT ck_teacher_payout_net     CHECK (collected_net = collected_gross - refunded),
    -- Les deux parts somment exactement ce que la paie partage : pas un
    -- centime ne se perd à l'arrondi.
    CONSTRAINT ck_teacher_payout_parts   CHECK (teacher_amount + school_amount = base_delta),
    -- La Paie_Initiale partage tout l'encaissé, rémunère l'enseignant, et ne
    -- désigne aucune autre paie.
    CONSTRAINT ck_teacher_payout_initial CHECK (
        kind <> 'INITIAL'
        OR (initial_payout_id IS NULL AND teacher_amount > 0 AND base_delta = collected_net)),
    -- Une Régularisation désigne sa Paie_Initiale et porte un écart non nul.
    CONSTRAINT ck_teacher_payout_regularization CHECK (
        kind <> 'REGULARIZATION' OR (initial_payout_id IS NOT NULL AND teacher_amount <> 0)),
    -- Même règle d'annulation que l'Encaissement (V6) : une paie annulée dit
    -- quand, par qui et pourquoi ; une paie active n'en porte aucune trace.
    CONSTRAINT ck_teacher_payout_cancellation CHECK (
        CASE status
            WHEN 'CANCELLED' THEN
                cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL
                AND cancel_reason_type IS NOT NULL
            WHEN 'ACTIVE' THEN
                cancelled_at IS NULL AND cancelled_by IS NULL
                AND cancel_reason_type IS NULL AND cancel_reason_text IS NULL
            ELSE TRUE
        END),
    CONSTRAINT ck_teacher_payout_cancel_reason_other CHECK (
        cancel_reason_type IS DISTINCT FROM 'OTHER'
        OR (cancel_reason_text IS NOT NULL AND length(btrim(cancel_reason_text)) > 0)),
    CONSTRAINT ck_teacher_payout_replaced_is_cancelled CHECK (
        replaced_by_id IS NULL OR status = 'CANCELLED'),
    CONSTRAINT ck_teacher_payout_not_self CHECK (
        replaces_id <> id AND replaced_by_id <> id AND initial_payout_id <> id)
);

-- Un numéro de paie ne sert qu'une fois, quoi qu'il arrive.
CREATE UNIQUE INDEX uk_teacher_payout_number ON teacher_payout (payout_number);

-- Au plus une Paie_Initiale active par série : le filet de sécurité derrière
-- le verrou de série du service, même sous deux confirmations simultanées.
CREATE UNIQUE INDEX uk_teacher_payout_initial_active
    ON teacher_payout (series_id) WHERE kind = 'INITIAL' AND status = 'ACTIVE';

-- Paies d'un enseignant, la plus récente d'abord ; paies d'une série.
CREATE INDEX idx_teacher_payout_teacher ON teacher_payout (teacher_id, paid_at DESC);
CREATE INDEX idx_teacher_payout_series  ON teacher_payout (series_id);

-- ---------------------------------------------------------------------
-- 3. Le compteur des numéros de paie
-- ---------------------------------------------------------------------
-- Même modèle que receipt_counter (V6) : une ligne, verrouillée à chaque
-- attribution, modifiée dans la transaction de la paie. Une paie refusée, ou
-- un aperçu annulé, ne consomme aucun numéro.
CREATE TABLE payout_counter (
    id              BIGINT   PRIMARY KEY,
    counter_year    INTEGER  NOT NULL,
    last_rank       INTEGER  NOT NULL,
    CONSTRAINT ck_payout_counter_single CHECK (id = 1),
    CONSTRAINT ck_payout_counter_rank   CHECK (last_rank >= 0)
);
INSERT INTO payout_counter (id, counter_year, last_rank) VALUES (1, 0, 0);

-- ---------------------------------------------------------------------
-- 4. Les impressions d'un bordereau
-- ---------------------------------------------------------------------
-- Modèle refund_receipt_issuance (V2) : à partir du rang 2, le bordereau
-- porte « DUPLICATA ». Un bordereau réimprimé sans mention peut servir deux
-- fois.
CREATE TABLE payout_slip_issuance (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_id   BIGINT        NOT NULL,
    rank        INTEGER       NOT NULL,
    issued_at   TIMESTAMP(3)  NOT NULL,
    issued_by   VARCHAR(255)  NOT NULL,
    CONSTRAINT fk_payout_slip_payout FOREIGN KEY (payout_id) REFERENCES teacher_payout (id),
    CONSTRAINT uk_payout_slip_rank   UNIQUE (payout_id, rank),
    CONSTRAINT ck_payout_slip_rank   CHECK (rank >= 1)
);
